### ISSUE TITLE
Unable to filter Boolean type of column 

### ISSUE THREAD

**Issue by Pratikbhajankar** [Sgitario/Java-Spring-LAB#1]
Hi 
Saw your implementation and it's pretty good. 
But in my case, I am trying to filter the record based on some boolean value. 
I have passed the below payload. 

```
{"page":0,
"size":50,
"filter":["active::false"]
}
```

getting blow error 

```
{
    "timestamp": "2022-11-16T14:00:17.512+0000",
    "status": 500,
    "error": "Internal Server Error",
    "message": "Parameter value [false] did not match expected type [java.lang.Boolean (n/a)]; nested exception is java.lang.IllegalArgumentException: Parameter value [false] did not match expected type [java.lang.Boolean (n/a)]",
    "path": "/items"
}
```

Can you please add support for boolean value.

Thanks in advance

**Comment by Sgitario** [comment]
Thanks for using this repo! I've just added support for boolean and numbers, see commit: https://github.com/Sgitario/Java-Spring-LAB/commit/c3d4b5fa927325cbc9fa40c9906319d7110de8b5
